# Generated by Django 3.2.11 on 2022-02-13 17:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmr',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Time created'),
            preserve_default=False,
        ),
    ]
