# Generated by Django 3.2.11 on 2022-02-13 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0002_bmr_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmr',
            name='goal',
            field=models.IntegerField(choices=[(0, 'Fat loss'), (1, 'Maintenance'), (2, 'Muscle gain')], default=1),
            preserve_default=False,
        ),
    ]
