# Generated by Django 3.2.11 on 2022-02-27 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0008_auto_20220227_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
