# Generated by Django 3.2.11 on 2022-02-27 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0010_auto_20220227_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='ingredient_id',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='recipe_id',
            new_name='recipe',
        ),
    ]
