# Generated by Django 3.2.11 on 2022-03-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0011_auto_20220227_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='mealplans.RecipeIngredient', to='mealplans.Ingredient'),
        ),
    ]
